Alter table AUDIT_CHECK_LIST_TBL ADD IF_OTHER NUMBER(2,0);
update AUDIT_CHECK_LIST_TBL set IF_OTHER = 0;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 95;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 105;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 48;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 57;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 62;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 13;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 16;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 26;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 38;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 8;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 64;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 66;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 75;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 84;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 92;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 44;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 6;
COMMIT;

update AUDIT_CHECK_LIST_TBL set IF_OTHER = 1 WHERE NODE_ID =1 AND NODE_ELEMENT_ORDER= 42;
COMMIT;

-----------------------------------------------------------------------------------------------

alter table AUDIT_INCIDENT_TBL ADD OTHER_PROC_EXAMINE_DES VARCHAR2(1000 CHAR);
alter table AUDIT_INCIDENT_TBL ADD REPLY_FLAG NUMBER(3,0);



alter table AUDIT_INCIDENT_LOG ADD OTHER_PROC_EXAMINE_DES VARCHAR2(1000 CHAR);