

ALTER TABLE AUDIT_CASE_TBL ADD RM_OVERALL_COMMENT BLOB;
ALTER TABLE AUDIT_CASE_TBL ADD CURRENT_ASSIGNED_DIV VARCHAR2(5 BYTE);
ALTER TABLE AUDIT_CASE_TBL ADD RM_OVERALL_COMMENT_STRING VARCHAR2(255 CHAR);
ALTER TABLE AUDIT_CASE_TBL ADD OVERALL_RISK_CODE VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_CASE_TBL ADD OVERALL_RISK VARCHAR2(20 BYTE);

----for AUDIT_COMMENT_TBL ------
ALTER TABLE AUDIT_COMMENT_TBL
    ADD NEXT_USER_DIV VARCHAR2(3 BYTE);

UPDATE AUDIT_DOC_TBL SET DEL_FLAG='0';
COMMIT;



ALTER TABLE AUDIT_INCIDENT_LOG ADD MAIN_CASE_ID NUMBER(10,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD CHILD_CASE_ID NUMBER(10,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD INCIDENT_ID NUMBER(10,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD AUDIT_STATUS VARCHAR2(5 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD IMPACT VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LIKELIHOOD VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD OVERALL_RISK VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD SAMPLE_COUNT NUMBER(10,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD ISSUE_COUNT NUMBER(10,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD POTENTIAL_IMPACT VARCHAR2(4000 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD RECOMMENDATION VARCHAR2(4000 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD ROOT_CAUSE VARCHAR2(200 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD DETAILS_ROOT_CAUSE VARCHAR2(1000 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD AGREE_WITH_AUDIT NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD RESPONSIBLE_OFFICER VARCHAR2(100 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD RECTIFIED NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD RECTIFY_DATE TIMESTAMP (6);
ALTER TABLE AUDIT_INCIDENT_LOG ADD COMMENT_HEADING VARCHAR2(200 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD INCIDENT_COMMENT BLOB;
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE1 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE_ORDER1 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE2 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE_ORDER2 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE3 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE_ORDER3 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE4 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE_ORDER4 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE5 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE_ORDER5 VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD INCIDENT_CREATED_USER VARCHAR2(8 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD INCIDENT_CURRENT_ASSIGNED_USER VARCHAR2(8 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD INCIDENT_CREATED_DIV VARCHAR2(5 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD INCIDENT_CURRENT_ASSIGNED_DIV VARCHAR2(5 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD HR NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD POLICIES_AND_PROCEDURE NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD PROCESS_AND_EXECUTION NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD IT NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD PERFORMANCE_MEASUREMENT NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD TARGET_DATE TIMESTAMP (6);
ALTER TABLE AUDIT_INCIDENT_LOG ADD DEL_FLAG NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE_ID VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_NODE_ELEMENT_ORDER VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD AUDIT_SECTION VARCHAR2(20 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD BR_COMMENT_FLAG NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD FYI NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD OVERALL_INCIDENT_STATUS VARCHAR2(2 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD FOLLOW_UP_RECTIFIED NUMBER(2,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD FOLLOW_UP_RECTIFIED_DATE TIMESTAMP (6);
ALTER TABLE AUDIT_INCIDENT_LOG ADD FOLLOW_UP_TARGET_DATE TIMESTAMP (6);
ALTER TABLE AUDIT_INCIDENT_LOG ADD FOLLOW_UP_RESPONSIBLE_OFFICER VARCHAR2(100 BYTE);
ALTER TABLE AUDIT_INCIDENT_LOG ADD BR_COMMENT BLOB;
ALTER TABLE AUDIT_INCIDENT_LOG ADD FUR_COMMENT BLOB;
ALTER TABLE AUDIT_INCIDENT_LOG ADD FOLLOW_UP_COMMENT BLOB;
ALTER TABLE AUDIT_INCIDENT_LOG ADD RM_COMMENT BLOB;
ALTER TABLE AUDIT_INCIDENT_LOG ADD OVERALL_RISK_VALUE FLOAT(126);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_MODIFIED_DIV VARCHAR2(2550 CHAR);
ALTER TABLE AUDIT_INCIDENT_LOG ADD LAST_MODIFIED_LEVEL VARCHAR2(255 CHAR);
ALTER TABLE AUDIT_INCIDENT_LOG ADD CHANGES_FOR_AUDIT_COMMENT VARCHAR2(255 CHAR);
ALTER TABLE AUDIT_INCIDENT_LOG ADD FOLLOW_UP_AGREED NUMBER(10,0);
ALTER TABLE AUDIT_INCIDENT_LOG ADD QA_COMMENT BLOB;



ALTER TABLE AUDIT_INCIDENT_TBL ADD YEAR VARCHAR2(255 CHAR);
ALTER TABLE AUDIT_INCIDENT_TBL ADD FOLLOW_UP_AGREED NUMBER;
ALTER TABLE AUDIT_INCIDENT_TBL ADD CHANGES_FOR_AUDIT_COMMENT VARCHAR2(4000 BYTE);
ALTER TABLE AUDIT_INCIDENT_TBL ADD QA_COMMENT BLOB;



ALTER TABLE AUDIT_REPORT_SUMMARY ADD STAFF_STR6 VARCHAR2(50 BYTE);
ALTER TABLE AUDIT_REPORT_SUMMARY ADD STAFF_STR7 VARCHAR2(50 BYTE);
ALTER TABLE AUDIT_REPORT_SUMMARY ADD STAFF_STR8 VARCHAR2(50 BYTE);
ALTER TABLE AUDIT_REPORT_SUMMARY ADD STAFF_STR9 VARCHAR2(50 BYTE);
ALTER TABLE AUDIT_REPORT_SUMMARY ADD STAFF_STR10 VARCHAR2(50 BYTE);

ALTER TABLE AUDIT_DOC_TBL
    ADD ENABLE_FOR_BR NUMBER(2,0);

UPDATE AUDIT_DOC_TBL SET ENABLE_FOR_BR=0;
COMMIT;



