  CREATE TABLE "AUDIT_CASE_TBL" 
   (	"DOC_CASE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CASE_CREATED_DATE" TIMESTAMP (6), 
	"CASE_CREATED_USER" VARCHAR2(8 BYTE), 
	"CASE_LAST_ACTION_STATUS" NUMBER(2,0), 
	"CASE_SPECIAL_COMMENT_VARCHAR" VARCHAR2(1000 BYTE), 
	"CASE_LAST_ACTION_DATE" TIMESTAMP (6), 
	"CASE_LAST_ACTION_USER" VARCHAR2(8 BYTE), 
	"CASE_LAST_ACTION_USER_LEVEL" NUMBER(4,0), 
	"LAST_NODE_ID" NUMBER(8,0), 
	"CASE_CREATED_DIV" VARCHAR2(5 BYTE), 
	"LAST_NODE_ELEMENT_ORDER" NUMBER(3,0), 
	"CASE_CREATED_USER_LEVEL" NUMBER(4,0), 
	"CURRENT_ASSIGNED_USER" VARCHAR2(8 BYTE), 
	"CURRENT_ASSIGNED_USER_LEVEL" NUMBER(4,0), 
	"CASE_SPECIAL_COMMENT" BLOB, 
	"CASE_RESPONSIBLE_USER" VARCHAR2(8 BYTE), 
	"AUDIT_AREA" VARCHAR2(20 BYTE), 
	"RISK_CAL_CODE" VARCHAR2(20 BYTE), 
	"AUDIT_MODE" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER(4,0), 
	"COVER_FROM" TIMESTAMP (6), 
	"COVER_TO" TIMESTAMP (6), 
	"EXAM_PERIOD_FROM" TIMESTAMP (6), 
	"EXAM_PERIOD_TO" TIMESTAMP (6), 
	"AUDIT_DIV" VARCHAR2(5 BYTE), 
	"AUDIT_ASSIGN_OBJ" RAW(255), 
	"CURRENT_ASSIGN_USER_NAME" VARCHAR2(255 CHAR), 
	"CREATED_USER_NAME" VARCHAR2(255 CHAR), 
	"AUDIT_DIV_DESC" VARCHAR2(100 BYTE), 
	"OVERALL_AUDIT_STATUS" VARCHAR2(2 BYTE), 
	"AUDIT_REPORT_REF_NUM" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "AUDIT_CASE_TBL_PK" PRIMARY KEY ("DOC_CASE_ID"),
	 CONSTRAINT "UNIQUE_REF" UNIQUE ("AUDIT_REPORT_REF_NUM") DISABLE);
	
  
  
	CREATE TABLE "AUDIT_CHECK_LIST_TBL" 
  	 (	"NODE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"NODE_ELEMENT_ORDER" NUMBER(4,0) NOT NULL ENABLE, 
	"PARENT_NODE" NUMBER(8,0) NOT NULL ENABLE, 
	"PARENT_NODE_ORDER" NUMBER(4,0) NOT NULL ENABLE, 
	"NODE_DESCRIPTION" VARCHAR2(1200 BYTE), 
	"NODE_STATUS" NUMBER(2,0), 
	"NODE_COMMENTS" VARCHAR2(1000 BYTE), 
	"SCORE_CALCULATE_CODE" VARCHAR2(16 BYTE), 
	"CAL_YEAR" VARCHAR2(8 BYTE), 
	"MAIN_ID" VARCHAR2(5 BYTE), 
	"SUB_ID" VARCHAR2(6 BYTE), 
	 CONSTRAINT "AUDIT_CHECK_LIST_TBL_PK" PRIMARY KEY ("NODE_ID", "NODE_ELEMENT_ORDER"));
	
	

CREATE TABLE "AUDIT_CHILD_CASE_TBL" 
   (	"CHILD_CASE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CASE_CREATED_DATE" TIMESTAMP (6), 
	"CASE_CREATED_USER" VARCHAR2(8 BYTE), 
	"CASE_LAST_ACTION_STATUS" NUMBER(2,0), 
	"CASE_SPECIAL_COMMENT_VARCHAR" VARCHAR2(1000 BYTE), 
	"CASE_LAST_ACTION_DATE" TIMESTAMP (6), 
	"CASE_LAST_ACTION_USER" VARCHAR2(8 BYTE), 
	"CASE_LAST_ACTION_USER_LEVEL" NUMBER(4,0), 
	"LAST_NODE_ID" NUMBER(8,0), 
	"CASE_CREATED_DIV" VARCHAR2(5 BYTE), 
	"LAST_NODE_ELEMENT_ORDER" NUMBER(3,0), 
	"CASE_CREATED_USER_LEVEL" NUMBER(4,0), 
	"CURRENT_ASSIGNED_USER" VARCHAR2(8 BYTE), 
	"CURRENT_ASSIGNED_USER_LEVEL" NUMBER(4,0), 
	"CASE_SPECIAL_COMMENT" BLOB, 
	"AUDIT_AREA" VARCHAR2(16 BYTE), 
	"RISK_CAL_CODE" VARCHAR2(20 BYTE), 
	"AUDIT_MODE" VARCHAR2(20 BYTE), 
	"YEAR" NVARCHAR2(20), 
	"COVER_FROM" TIMESTAMP (6), 
	"COVER_TO" TIMESTAMP (6), 
	"EXAM_PERIOD_FROM" TIMESTAMP (6), 
	"EXAM_PERIOD_TO" TIMESTAMP (6), 
	"MAIN_CASE_ID" NUMBER(10,0), 
	"CASE_RESPONSIBLE_USER" VARCHAR2(255 CHAR), 
	 CONSTRAINT "AUDIT_CHILD_CASE_TBL_PK" PRIMARY KEY ("CHILD_CASE_ID"));
	

	CREATE TABLE "AUDIT_COMMENT_TBL" 
   (	"MAIN_CASE_ID" NUMBER, 
	"COMMENT_TYPE" VARCHAR2(20 BYTE), 
	"COMMENT_USER_ID" VARCHAR2(20 BYTE), 
	"COMMENT_USER_DIV" VARCHAR2(3 BYTE), 
	"AUDIT_COMMENT" BLOB, 
	"COMMENT_DATE" TIMESTAMP (6), 
	"NEXT_USER" VARCHAR2(20 BYTE), 
	"ACTION" NUMBER(2,0));
	

	CREATE TABLE "AUDIT_FINANCIAL_HIGHLIGHTS" 
   (	"MAIN_CASE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_USER" VARCHAR2(20 BYTE), 
	"COMMENTS" BLOB, 
	"CREATED_DATE" TIMESTAMP (6), 
	"FID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "AUDIT_FINANCIAL_HIGHLIGHTS_PK" PRIMARY KEY ("MAIN_CASE_ID"));
	
	


CREATE TABLE "AUDIT_INCIDENT_LOG" 
   (	"ID" VARCHAR2(20 BYTE), 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"LAST_MODIFIED_BY" VARCHAR2(255 CHAR), 
	"LAST_MODIFIED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"ACTION" VARCHAR2(20 BYTE));
	
	


CREATE TABLE "AUDIT_INCIDENT_TBL" 
   (	"MAIN_CASE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CHILD_CASE_ID" NUMBER(10,0), 
	"INCIDENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AUDIT_STATUS" VARCHAR2(5 BYTE), 
	"IMPACT" VARCHAR2(20 BYTE), 
	"LIKELIHOOD" VARCHAR2(20 BYTE), 
	"OVERALL_RISK" VARCHAR2(20 BYTE), 
	"SAMPLE_COUNT" NUMBER(10,0), 
	"ISSUE_COUNT" NUMBER(10,0), 
	"POTENTIAL_IMPACT" VARCHAR2(4000 BYTE), 
	"RECOMMENDATION" VARCHAR2(4000 BYTE), 
	"ROOT_CAUSE" VARCHAR2(200 BYTE), 
	"DETAILS_ROOT_CAUSE" VARCHAR2(1000 BYTE), 
	"AGREE_WITH_AUDIT" NUMBER(2,0), 
	"RESPONSIBLE_OFFICER" VARCHAR2(100 BYTE), 
	"RECTIFIED" NUMBER(2,0), 
	"RECTIFY_DATE" TIMESTAMP (6), 
	"COMMENT_HEADING" VARCHAR2(200 BYTE), 
	"INCIDENT_COMMENT" BLOB, 
	"LAST_NODE1" VARCHAR2(20 BYTE), 
	"LAST_NODE_ORDER1" VARCHAR2(20 BYTE), 
	"LAST_NODE2" VARCHAR2(20 BYTE), 
	"LAST_NODE_ORDER2" VARCHAR2(20 BYTE), 
	"LAST_NODE3" VARCHAR2(20 BYTE), 
	"LAST_NODE_ORDER3" VARCHAR2(20 BYTE), 
	"LAST_NODE4" VARCHAR2(20 BYTE), 
	"LAST_NODE_ORDER4" VARCHAR2(20 BYTE), 
	"LAST_NODE5" VARCHAR2(20 BYTE), 
	"LAST_NODE_ORDER5" VARCHAR2(20 BYTE), 
	"INCIDENT_CREATED_USER" VARCHAR2(8 BYTE), 
	"INCIDENT_CURRENT_ASSIGNED_USER" VARCHAR2(8 BYTE), 
	"INCIDENT_CREATED_DIV" VARCHAR2(5 BYTE), 
	"INCIDENT_CURRENT_ASSIGNED_DIV" VARCHAR2(5 BYTE), 
	"HR" NUMBER(2,0), 
	"POLICIES_AND_PROCEDURE" NUMBER(2,0), 
	"PROCESS_AND_EXECUTION" NUMBER(2,0), 
	"IT" NUMBER(2,0), 
	"PERFORMANCE_MEASUREMENT" NUMBER(2,0), 
	"TARGET_DATE" TIMESTAMP (6), 
	"DEL_FLAG" NUMBER(2,0), 
	"LAST_NODE_ID" VARCHAR2(20 BYTE), 
	"LAST_NODE_ELEMENT_ORDER" VARCHAR2(20 BYTE), 
	"AUDIT_SECTION" VARCHAR2(20 BYTE), 
	"BR_COMMENT_FLAG" NUMBER(2,0), 
	"FYI" NUMBER(2,0), 
	"OVERALL_INCIDENT_STATUS" VARCHAR2(2 BYTE), 
	"FOLLOW_UP_RECTIFIED" NUMBER(2,0), 
	"FOLLOW_UP_RECTIFIED_DATE" TIMESTAMP (6), 
	"FOLLOW_UP_TARGET_DATE" TIMESTAMP (6), 
	"FOLLOW_UP_RESPONSIBLE_OFFICER" VARCHAR2(100 BYTE), 
	"BR_COMMENT" BLOB, 
	"FUR_COMMENT" BLOB, 
	"FOLLOW_UP_COMMENT" BLOB, 
	"BM_COMMENT" VARCHAR2(255 CHAR), 
	 CONSTRAINT "AUDIT_INCIDENT_TBL_PK" PRIMARY KEY ("INCIDENT_ID"),
   CONSTRAINT "CHILD_CASE_ID_FK" FOREIGN KEY ("CHILD_CASE_ID") REFERENCES "AUDIT_CHILD_CASE_TBL" ("CHILD_CASE_ID") ENABLE,
   CONSTRAINT "MAIN_CASE_ID_FK" FOREIGN KEY ("MAIN_CASE_ID") REFERENCES "AUDIT_CASE_TBL" ("DOC_CASE_ID") ENABLE );
   



CREATE TABLE "AUDIT_INSIDENT_COMMENT_TBL" 
   (	"MAIN_CASE_ID" NUMBER, 
	"CHILD_CASE_ID" NUMBER, 
	"INSIDENT_ID" NUMBER, 
	"COMMENT_USER_TYPE" VARCHAR2(20 BYTE), 
	"COMMENT_USER_ID" VARCHAR2(20 BYTE), 
	"COMMENT_USER_DIV" VARCHAR2(3 BYTE), 
	"INSIDENT_COMMENT" BLOB, 
	"AGREE_WITH_AUDIT" NUMBER(2,0), 
	"RESPONSIBLE_OFFICER" VARCHAR2(100 BYTE), 
	"RECTIFIED" NUMBER(2,0), 
	"RECTIFY_DATE" TIMESTAMP (6), 
	"TARGET_DATE" TIMESTAMP (6), 
	"COMMENT_ADDED_DATE" TIMESTAMP (6));
	


  CREATE TABLE "AUDIT_OVERALL_RISK_CAL_DETAILS" 
   (	"REPORT_GEN_YEAR" NUMBER(4,0), 
	"EXTREME_VAL" FLOAT(126), 
	"HIGH_VAL" FLOAT(126), 
	"MEDIUM_VAL" FLOAT(126), 
	"LOW_VAL" FLOAT(126), 
	"GENERATED_CODE" VARCHAR2(20 BYTE));
	


CREATE TABLE "AUDIT_OVERALL_RISK_FACTORS" 
   (	"SIGNIFICANCE" VARCHAR2(20 BYTE), 
	"LIKELIHOOD" VARCHAR2(20 BYTE), 
	"OVERALLRISK" VARCHAR2(20 BYTE), 
	"ACTIVE_STATUS" NUMBER, 
	"CAL_YEAR" NUMBER(4,0), 
	"RISK_CAL_CODE" VARCHAR2(20 BYTE));
	
	

CREATE TABLE "AUDIT_REPORT_SUMMARY" 
   (	"MAIN_CASE_ID" NUMBER NOT NULL ENABLE, 
	"EXIT_MEETING_DATE" TIMESTAMP (6), 
	"DRAFT_REPORT_ISSUED_DATE" TIMESTAMP (6), 
	"RESPONSE_DATE" TIMESTAMP (6), 
	"RESPONSE_RECEIVE_DATE" TIMESTAMP (6), 
	"FINAL_REPORT_ISSUED_DATE" TIMESTAMP (6), 
	"REVIEWER1" VARCHAR2(50 BYTE), 
	"REVIEWER2" VARCHAR2(50 BYTE), 
	"REVIEWER3" VARCHAR2(50 BYTE), 
	"REVIEWER4" VARCHAR2(50 BYTE), 
	"REVIEWER5" VARCHAR2(50 BYTE), 
	"EXAMINER1" VARCHAR2(50 BYTE), 
	"EXAMINER2" VARCHAR2(50 BYTE), 
	"EXAMINER3" VARCHAR2(50 BYTE), 
	"EXAMINER4" VARCHAR2(50 BYTE), 
	"EXAMINER5" VARCHAR2(50 BYTE), 
	"EXAMINER6" VARCHAR2(50 BYTE), 
	"BR_MANAGER" VARCHAR2(50 BYTE), 
	"ASST_MANAGER" VARCHAR2(50 BYTE), 
	"STAFF_STR1" VARCHAR2(50 BYTE), 
	"STAFF_STR2" VARCHAR2(50 BYTE), 
	"STAFF_STR3" VARCHAR2(50 BYTE), 
	"STAFF_STR4" VARCHAR2(50 BYTE), 
	"STAFF_STR5" VARCHAR2(50 BYTE), 
	"ADDED_USER" VARCHAR2(8 BYTE), 
	"ADDED_USER_DIV" VARCHAR2(5 BYTE), 
	"ADDED_USER_LEVEL" VARCHAR2(5 BYTE), 
	"ADDED_DATE" TIMESTAMP (6), 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "AUDIT_REPORT_SUMMARY_PK" PRIMARY KEY ("MAIN_CASE_ID"),
   CONSTRAINT "MAIN_CASE_ID_FK2" FOREIGN KEY ("MAIN_CASE_ID") REFERENCES "AUDIT_CASE_TBL" ("DOC_CASE_ID") ENABLE);
   


CREATE TABLE "AUDIT_RISK_FACTOR_TBL" 
   (	"CAL_CODE" VARCHAR2(20 BYTE), 
	"CAL_YEAR" NUMBER(4,0), 
	"MIN_VAL" FLOAT(126), 
	"MAX_VAL" FLOAT(126), 
	"RISK_FACTOR" VARCHAR2(5 BYTE), 
	"RISK_FACTOR_DESC" VARCHAR2(2000 BYTE));
	
	

 CREATE TABLE "AUDIT_SECTION_TBL" 
   (	"PARENT_NODE" NUMBER(8,0) NOT NULL ENABLE, 
	"PARENT_NODE_ORDER" NUMBER(3,0) NOT NULL ENABLE, 
	"DIV_CODE" VARCHAR2(4 BYTE), 
	"AUDIT_AREA" VARCHAR2(8 BYTE), 
	"AUDIT_MODE" VARCHAR2(8 BYTE), 
	"SECTION_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"SECTION_AREA" VARCHAR2(12 BYTE), 
	"YEAR" VARCHAR2(8 BYTE), 
	 CONSTRAINT "AUDIT_SECTION_TBL_PK" PRIMARY KEY ("PARENT_NODE", "PARENT_NODE_ORDER"));
	
	
	
	
	
   
   
   