TRUNCATE TABLE AUDIT_CASE_TBL;
/
TRUNCATE TABLE AUDIT_CHECK_LIST_TBL;
/
TRUNCATE TABLE AUDIT_CHILD_CASE_TBL;
/
TRUNCATE TABLE AUDIT_COMMENT_TBL;
/
TRUNCATE TABLE AUDIT_FINANCIAL_HIGHLIGHTS;
/
TRUNCATE TABLE AUDIT_INCIDENT_LOG;
/
TRUNCATE TABLE AUDIT_INCIDENT_TBL;
/
TRUNCATE TABLE AUDIT_REPORT_SUMMARY;
/
TRUNCATE TABLE AUDIT_SECTION_TBL;
/